### ISSUE TITLE
Improve file structure in examples

### ISSUE THREAD

**Issue by momegas** [squaredev-io/explainable-ai#6]
In examples folder, the structure is not ideal at the moment. I propose a result oriented structure is the following:

- Computer Vision
  - Lime
  - Gradcam
  - ...
- NLP
  - Lime
  - ...
 - Tabular
   - Lime
   
Or something similar per model.
@stavrostheocharis @NickNtamp what do you think?

**Comment by NickNtamp** [comment]
Just for enhance clarity, I would suggest to use "XAI for Computer Vision tasks", "XAI for NLP tasks" etc.
As we will publish the CV repo, to avoid any conflicts there.
Thanks
cc: @momegas @stavrostheocharis

**Comment by stavrostheocharis** [comment]
I think that we should not go into such depth in structure. I think that just names like Lime-NLP.ipynb at the titles of the notebooks is sufficient. In the end the same algos are applied (for example Lime is used for NLP, Tabular, or CV it does not need to be split in different folders).

**Comment by momegas** [comment]
As long as its clear and somehow structured, its fine for me.

**Comment by stavrostheocharis** [comment]
It needs some parts for sure, we can discuss them later
